name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if you want to deploy from a different branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Create config.js
      run: echo "const googleApiKey = '${{ secrets.GOOGLE_API_KEY }}';" > config.js

    - name: Build project
      run: npm run build  # If you have a build step

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public  # Change this to your build output directory
